### ISSUE TITLE
Missing /examples

### ISSUE THREAD

**Issue by bermi** [lidofinance/innernet-playbooks#3]
On the README, you mention there's an `/examples` directory with some `libvirt` examples but there's no such a directory on any of the branches. Is this something you could push?

Thank you for this playbook!

**Comment by amarao** [comment]
Thank you for pointing this out! I'll update readme.

All libvirt-related playbooks were incorporated into `/molecule` directory.  (Mostly in create/destroy.yml). To use this thing properly you need to use Molecule. Just install molecule and other requirements and run `molecule create` on libvirt-enabled host.
